apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: hipstershop
build:
  artifacts:
    # image tags are relative; to specify an image repo (e.g. GCR), you
    # must provide a "default repo" using one of the methods described
    # here:
    # https://skaffold.dev/docs/concepts/#image-repository-handling
    - image: email
      context: service/email
    - image: productcatalog
      context: service/productcatalog
    - image: recommendation
      context: service/recommendation
    - image: shipping
      context: service/shipping
    - image: checkout
      context: service/checkout
    - image: payment
      context: service/payment
    - image: currency
      context: service/currency
    - image: cart
      context: service/cart
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: service/frontend
    - image: ad
      context: service/ad
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
    concurrency: 10
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/adservice.yaml
      - ./infra/k8s/cartservice.yaml
      - ./infra/k8s/checkoutservice.yaml
      - ./infra/k8s/currencyservice.yaml
      - ./infra/k8s/emailservice.yaml
      - ./infra/k8s/frontend.yaml
      - ./infra/k8s/paymentservice.yaml
      - ./infra/k8s/productcatalogservice.yaml
      - ./infra/k8s/recommendationservice.yaml
      - ./infra/k8s/shippingservice.yaml
      - ./infra/k8s/gomicro.yaml
# profiles:
#   # "debug" profile replaces the default Dockerfile in cart with Dockerfile.debug,
#   # which enables debugging via skaffold.
#   #
#   # This profile is used by default when running skaffold debug.
#   - name: debug
#     activation:
#       - command: debug
#     patches:
#       - op: replace
#         path: /build/artifacts/7/docker/dockerfile
#         value: Dockerfile.debug

---
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: loadgenerator
requires:
  - configs: [hipstershop]
build:
  artifacts:
    - image: loadgenerator
      context: service/loadgenerator
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/loadgenerator.yaml
